name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4


    - name: Install dependencies
      run: |
        sudo apt-get install libx11-dev
        sudo apt-get install libxext-dev
        cd linuxdoom-1.10 
        mkdir linux
        
    - name: Run check
      run: make all


